### PR TITLE
Add KubeJS Recipes compatibility (although it may not be good), patch the zh_cn language file

### PR DESCRIPTION
**Pull request by Qi-Month**
1.19 I haven't studied

### CODE REVIEW

**Comment by Lucreeper74** [comment]
Hey 👋 
Thanks a lot! I will see how to port this to 1.19
And I will check your PR this week-end !

**Comment by Qi-Month** [comment]
Thank you very much!  :)

**Comment by Lucreeper74** [comment]
Hey back @Qi-Month 👋

So, thanks you for you PR, this avoiding me to search documentation to see how to integrate a compatibility between Create Metallurgy and KubeJS.
So I have basically copied your commit into on my local branch and I have optimized your code to avoid flooding code.
I have also changed the way that you added heat requirement for Melting and Alloying recipe, I just take a look at how CreateKubeJS addon work. Cause like you have done it, if someone use LowHeated mod this would just not work with entries other than "heated" and "superheated".
For the update of zh_cn lang, I will take your json file in your commit to push it later.

That's why I'm going to reject your PR because I had your code redone, but thank you anyway it saved me a lot of time! No worries, that was not useless!

**Comment by Lucreeper74** [comment]
Here are the new code and I also updated zh_cn lang file with your credit!
[Add KubeJS compat](https://github.com/Lucreeper74/Create-Metallurgy/commit/45250057ea520f716fe4711f26609dd3ec36e40c) and [Update zh_cn lang](https://github.com/Lucreeper74/Create-Metallurgy/commit/f95beacd17459ae6c97e85f51b0952f0c6821f43)

**Pull request closed without merging**
