### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by IwasConfused**

### CODE REVIEW

**Comment by Lucreeper74** [comment]
Hey! Thank to support Create Metallurgy with chinese localization! 
I will merge your pull resquest soon and it will be available in the next update. You will be credited on Github ReadMe + Modrinth and Curseforge mod page. So what nickname you want to get ?

**Comment by IwasConfused** [comment]
> Hey! Thank to support Create Metallurgy with chinese localization! I will merge your pull resquest soon and it will be available in the next update. You will be credited on Github ReadMe + Modrinth and Curseforge mod page. So what nickname you want to get ?

Please call me Tellurium.
Looking forward to more updates in the future!

**Comment by Lucreeper74** [comment]
All right, thanks!

**Comment by Lucreeper74** [comment]
Hey @IwasConfused !

Currently Create Metallurgy v0.0.7 in the pipes. I have made a special channel on the Discord for translators and others contributors. I would like to add you but I don't know what is your Discord.
This channel will be used to anticipate release to let translators to update theirs translation.

Ping me on Discord directly. I may not see your message here...

**Pull request merged**
